# Quadtree Block Compression Config
Quadtree:
  # Minimal similarity of base and upsampled image required to be a leaf
  SimilarityCutoff: 0.9
  # Interpolation algorithm used to downsample base image
  DownsamplingInterpolator: NearestNeighbor
  # Interpolation algorithm used to upsample downsampled image
  UpsamplingInterpolator: CatmullRom

# Encoding Config
Encoding:
  # Underlying archive format of the encoded file
  ArchiveFormat: "gzip"
  SkipOutOfBoundsBlocks:
    # Should blocks that are not visible be skipped during encoding
    Enable: False
  DeduplicateBlocks:
    # Should similar blocks be deduplicated during encoding?
    Enable: False
    # How similar do blocks have to be to be deduplicated?
    MinimalSimilarity: 0.9

# Visualization Config
Visualization:
  # Should the visualizations be created?
  Enable: False
